#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: 'Konductor | Sparta | VPC'
  hosts: localhost
  vars:
    module: "destroy"
    ansible_name_module: " Konductor | Sparta | VPC"
  vars_files:
    - vars/aws.yml
  tasks:

    - name: Purge security components using CloudFormation
      cloudformation:
        stack_name: "{{ infrastructure_name }}-security"
        state: absent
      register: r_cf_security

    - name: Debug output for security components creation
      debug:
        var: r_cf_security

    - name: Purge VPC using CloudFormation
      cloudformation:
        stack_name: "{{ infrastructure_name }}-vpc"
        state: absent
      register: r_cf_vpc

    - name: Debug output for VPC creation
      debug:
        var: r_cf_vpc

